import tkinter as tk
window = tk.Tk()
window.geometry("720x476")
window.title("Simple Calculator")
def clicked(ARGS):
    Textbox.config(state="normal")
    Textbox.insert(tk.INSERT, ARGS)
    Textbox.config(state="disabled")
def CLEAR():
    Textbox.config(state="normal")
    Textbox.delete(1.0,tk.END )
    Textbox.config(state="disabled")
def BACK():
    Textbox.config(state="normal")
    Ct = Textbox.get(1.0,tk.END)
    nt = Ct[:-2]
    Textbox.delete(1.0,tk.END )
    Textbox.insert(tk.INSERT, nt)
    Textbox.config(state="disabled")
def MATH():
    try:
        expression = Textbox.get(1.0, tk.END).strip()
        result = str(eval(expression))
        Textbox.config(state="normal")
        Textbox.delete(1.0,tk.END )
        Textbox.insert(tk.INSERT, result)
        Textbox.config(state="disabled")
    except Exception as e:
        Textbox.config(state="normal")
        
        Textbox.delete(1.0,tk.END )
        Textbox.insert(tk.INSERT,str(e) + " error")
        Textbox.config(state="disabled")
label = tk.Label(window,text="CALCULATOR",font=("Papyrus",18))
label.pack(padx=10,pady=10)
Textbox = tk.Text(window, height = 7 , font=("Minecraft",18))
Textbox.pack()
Textbox.config(state="disabled")
Btnfrm = tk.Frame(window)
Btnfrm.columnconfigure(0 , weight=1)
Btnfrm.columnconfigure(1 , weight=1)
Btnfrm.columnconfigure(2 , weight=1)
Btnfrm.columnconfigure(3 , weight=1)
Btn1 = tk.Button(Btnfrm,text='1',font=("Minecraft",18),command=lambda : clicked('1'))
Btn1.grid(column=0,row=0,sticky=tk.W + tk.E)
Btn2 = tk.Button(Btnfrm,text='2',font=("Minecraft",18),command=lambda:clicked('2'))
Btn2.grid(column=0,row=1,sticky=tk.W + tk.E)
Btn3 = tk.Button(Btnfrm,text='3',font=("Minecraft",18),command= lambda:clicked('3'))
Btn3.grid(column=0,row=2,sticky=tk.W + tk.E)
Btn4 = tk.Button(Btnfrm,text='+',font=("Minecraft",18),command=lambda:clicked('+'))
Btn4.grid(column=0,row=3,sticky=tk.W + tk.E)
Btn5 = tk.Button(Btnfrm,text='4',font=("Minecraft",18),command=lambda:clicked('4'))
Btn5.grid(column=1,row=0,sticky=tk.W + tk.E)
Btn6 = tk.Button(Btnfrm,text='5',font=("Minecraft",18),command=lambda:clicked('5'))
Btn6.grid(column=1,row=1,sticky=tk.W + tk.E)
Btn7 = tk.Button(Btnfrm,text='6',font=("Minecraft",18),command=lambda:clicked('6'))
Btn7.grid(column=1,row=2,sticky=tk.W + tk.E)
Btn8 = tk.Button(Btnfrm,text='-',font=("Minecraft",18),command=lambda:clicked('-'))
Btn8.grid(column=1,row=3,sticky=tk.W + tk.E)
Btn9 = tk.Button(Btnfrm,text='7',font=("Minecraft",18),command=lambda:clicked('7'))
Btn9.grid(column=2,row=0,sticky=tk.W + tk.E)
Btn10 = tk.Button(Btnfrm,text='8',font=("Minecraft",18),command=lambda:clicked('8'))
Btn10.grid(column=2,row=1,sticky=tk.W + tk.E)
Btn11 = tk.Button(Btnfrm,text='9',font=("Minecraft",18),command=lambda:clicked('9'))
Btn11.grid(column=2,row=2,sticky=tk.W + tk.E)
Btn12 = tk.Button(Btnfrm,text='0',font=("Minecraft",18),command=lambda:clicked('0'))
Btn12.grid(column=2,row=3,sticky=tk.W + tk.E)
Btn13 = tk.Button(Btnfrm,text='% MOD',font=("Minecraft",18),command=lambda:clicked('%'))
Btn13.grid(column=3,row=0,sticky=tk.W + tk.E)
Btn14= tk.Button(Btnfrm,text='*',font=("Minecraft",18),command=lambda:clicked('*'))
Btn14.grid(column=3,row=1,sticky=tk.W + tk.E)
Btn15= tk.Button(Btnfrm,text='/',font=("Minecraft",18),command=lambda:clicked('/'))
Btn15.grid(column=3,row=2,sticky=tk.W + tk.E)
Btn16= tk.Button(Btnfrm,text='C',font=("Minecraft",18),command = lambda:CLEAR())
Btn16.grid(column=3,row=3,sticky=tk.W + tk.E)
Btn17= tk.Button(Btnfrm,text= '=',font=("Minecraft",18),command = lambda:MATH())
Btn17.grid(column=3,row=4,sticky=tk.W + tk.E)
Btn18= tk.Button(Btnfrm,text= 'BACKSPACE',font=("Minecraft",18),command=lambda:BACK())
Btn18.grid(column=2,row=4,sticky=tk.W + tk.E)
Btnfrm.pack(fill='x')
window.mainloop()
